/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Habit {
  'id' : HabitId,
  'name' : string,
  'color' : string,
  'emoji' : string,
}
export type HabitId = bigint;
export interface StreakData { 'bestStreak' : bigint, 'currentStreak' : bigint }
export interface UserActivity {
  'principal' : string,
  'habitCount' : bigint,
  'firstLogin' : bigint,
  'lastLogin' : bigint,
}
export interface UserAdminDetail {
  'principal' : string,
  'displayName' : string,
  'completionsToday' : bigint,
  'habits' : Array<Habit>,
  'firstLogin' : bigint,
  'lastLogin' : bigint,
  'weeklyCompletionRate' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addHabit' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteHabit' : ActorMethod<[HabitId], undefined>,
  'getAdminStats' : ActorMethod<[], Array<UserActivity>>,
  'getAdminUserDetails' : ActorMethod<[string], Array<UserAdminDetail>>,
  'getAllHabits' : ActorMethod<[], Array<Habit>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletionsForRange' : ActorMethod<
    [string, string],
    Array<[Habit, Array<string>]>
  >,
  'getStreakData' : ActorMethod<[], Array<[Habit, StreakData]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializePredefinedHabits' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordLogin' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPrincipal' : ActorMethod<[Principal], undefined>,
  'toggleCompletion' : ActorMethod<[HabitId, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];