/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HabitId = IDL.Nat;
export const UserActivity = IDL.Record({
  'principal' : IDL.Text,
  'habitCount' : IDL.Nat,
  'firstLogin' : IDL.Int,
  'lastLogin' : IDL.Int,
});
export const Habit = IDL.Record({
  'id' : HabitId,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'emoji' : IDL.Text,
});
export const UserAdminDetail = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'completionsToday' : IDL.Nat,
  'habits' : IDL.Vec(Habit),
  'firstLogin' : IDL.Int,
  'lastLogin' : IDL.Int,
  'weeklyCompletionRate' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StreakData = IDL.Record({
  'bestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHabit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteHabit' : IDL.Func([HabitId], [], []),
  'getAdminStats' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
  'getAdminUserDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserAdminDetail)],
      ['query'],
    ),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletionsForRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(Habit, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getStreakData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Habit, StreakData))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializePredefinedHabits' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordLogin' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'toggleCompletion' : IDL.Func([HabitId, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HabitId = IDL.Nat;
  const UserActivity = IDL.Record({
    'principal' : IDL.Text,
    'habitCount' : IDL.Nat,
    'firstLogin' : IDL.Int,
    'lastLogin' : IDL.Int,
  });
  const Habit = IDL.Record({
    'id' : HabitId,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'emoji' : IDL.Text,
  });
  const UserAdminDetail = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'completionsToday' : IDL.Nat,
    'habits' : IDL.Vec(Habit),
    'firstLogin' : IDL.Int,
    'lastLogin' : IDL.Int,
    'weeklyCompletionRate' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StreakData = IDL.Record({
    'bestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHabit' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteHabit' : IDL.Func([HabitId], [], []),
    'getAdminStats' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
    'getAdminUserDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserAdminDetail)],
        ['query'],
      ),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletionsForRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(Habit, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getStreakData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Habit, StreakData))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializePredefinedHabits' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordLogin' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'toggleCompletion' : IDL.Func([HabitId, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };