/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HabitId = IDL.Nat;
export const Achievement = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'earnedAt' : IDL.Int,
  'earned' : IDL.Bool,
});
export const UserActivity = IDL.Record({
  'principal' : IDL.Text,
  'habitCount' : IDL.Nat,
  'firstLogin' : IDL.Int,
  'lastLogin' : IDL.Int,
});
export const Habit = IDL.Record({
  'id' : HabitId,
  'goalTargetCount' : IDL.Nat,
  'difficulty' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'goalDeadline' : IDL.Text,
  'emoji' : IDL.Text,
  'reminderTime' : IDL.Text,
  'category' : IDL.Text,
  'customReminderMsg' : IDL.Text,
  'goalDescription' : IDL.Text,
});
export const UserAdminDetail = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'completionsToday' : IDL.Nat,
  'habits' : IDL.Vec(Habit),
  'firstLogin' : IDL.Int,
  'mobile' : IDL.Text,
  'lastLogin' : IDL.Int,
  'weeklyCompletionRate' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'habitOrder' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'accentColor' : IDL.Text,
  'avatarBase64' : IDL.Text,
  'streakTokens' : IDL.Nat,
  'mobile' : IDL.Text,
  'points' : IDL.Nat,
});
export const DetailedStats = IDL.Record({
  'totalDaysTracked' : IDL.Nat,
  'totalCompletions' : IDL.Nat,
  'currentStreakDays' : IDL.Nat,
  'habitsCompletedToday' : IDL.Nat,
  'bestStreakEver' : IDL.Nat,
  'averageCompletionRate' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'principal' : IDL.Text,
  'displayName' : IDL.Text,
  'points' : IDL.Nat,
});
export const StreakData = IDL.Record({
  'bestStreak' : IDL.Nat,
  'currentStreak' : IDL.Nat,
});
export const WeeklyChallenge = IDL.Record({
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'setBy' : IDL.Text,
  'targetCompletionsPerDay' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addHabit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addPoints' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteHabit' : IDL.Func([HabitId], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAdminStats' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
  'getAdminUserDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserAdminDetail)],
      ['query'],
    ),
  'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallengeMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getCompletionsForRange' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(Habit, IDL.Vec(IDL.Text)))],
      ['query'],
    ),
  'getDetailedStats' : IDL.Func([IDL.Text], [DetailedStats], ['query']),
  'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFriendLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getHabitNotes' : IDL.Func(
      [HabitId],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMoods' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getStreakData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Habit, StreakData))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyChallenge' : IDL.Func([], [IDL.Opt(WeeklyChallenge)], ['query']),
  'initializePredefinedHabits' : IDL.Func([], [], []),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinWeeklyChallenge' : IDL.Func([], [], []),
  'recordLogin' : IDL.Func([], [], []),
  'removeUser' : IDL.Func([IDL.Principal], [], []),
  'reorderHabits' : IDL.Func([IDL.Vec(HabitId)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveHabitNote' : IDL.Func([HabitId, IDL.Text, IDL.Text], [], []),
  'saveMood' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
  'setHabitGoal' : IDL.Func([HabitId, IDL.Text, IDL.Nat, IDL.Text], [], []),
  'setHabitReminderTime' : IDL.Func([HabitId, IDL.Text, IDL.Text], [], []),
  'setWeeklyChallenge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'spendStreakToken' : IDL.Func([HabitId, IDL.Text], [], []),
  'toggleCompletion' : IDL.Func([HabitId, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'updateHabit' : IDL.Func(
      [HabitId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HabitId = IDL.Nat;
  const Achievement = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'earnedAt' : IDL.Int,
    'earned' : IDL.Bool,
  });
  const UserActivity = IDL.Record({
    'principal' : IDL.Text,
    'habitCount' : IDL.Nat,
    'firstLogin' : IDL.Int,
    'lastLogin' : IDL.Int,
  });
  const Habit = IDL.Record({
    'id' : HabitId,
    'goalTargetCount' : IDL.Nat,
    'difficulty' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'goalDeadline' : IDL.Text,
    'emoji' : IDL.Text,
    'reminderTime' : IDL.Text,
    'category' : IDL.Text,
    'customReminderMsg' : IDL.Text,
    'goalDescription' : IDL.Text,
  });
  const UserAdminDetail = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'completionsToday' : IDL.Nat,
    'habits' : IDL.Vec(Habit),
    'firstLogin' : IDL.Int,
    'mobile' : IDL.Text,
    'lastLogin' : IDL.Int,
    'weeklyCompletionRate' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'habitOrder' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'accentColor' : IDL.Text,
    'avatarBase64' : IDL.Text,
    'streakTokens' : IDL.Nat,
    'mobile' : IDL.Text,
    'points' : IDL.Nat,
  });
  const DetailedStats = IDL.Record({
    'totalDaysTracked' : IDL.Nat,
    'totalCompletions' : IDL.Nat,
    'currentStreakDays' : IDL.Nat,
    'habitsCompletedToday' : IDL.Nat,
    'bestStreakEver' : IDL.Nat,
    'averageCompletionRate' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'principal' : IDL.Text,
    'displayName' : IDL.Text,
    'points' : IDL.Nat,
  });
  const StreakData = IDL.Record({
    'bestStreak' : IDL.Nat,
    'currentStreak' : IDL.Nat,
  });
  const WeeklyChallenge = IDL.Record({
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'setBy' : IDL.Text,
    'targetCompletionsPerDay' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addHabit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addPoints' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteHabit' : IDL.Func([HabitId], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getAdminStats' : IDL.Func([], [IDL.Vec(UserActivity)], ['query']),
    'getAdminUserDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserAdminDetail)],
        ['query'],
      ),
    'getAllHabits' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallengeMembersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getCompletionsForRange' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(Habit, IDL.Vec(IDL.Text)))],
        ['query'],
      ),
    'getDetailedStats' : IDL.Func([IDL.Text], [DetailedStats], ['query']),
    'getFollowing' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFriendLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getHabitNotes' : IDL.Func(
        [HabitId],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMoods' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getStreakData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Habit, StreakData))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyChallenge' : IDL.Func([], [IDL.Opt(WeeklyChallenge)], ['query']),
    'initializePredefinedHabits' : IDL.Func([], [], []),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinWeeklyChallenge' : IDL.Func([], [], []),
    'recordLogin' : IDL.Func([], [], []),
    'removeUser' : IDL.Func([IDL.Principal], [], []),
    'reorderHabits' : IDL.Func([IDL.Vec(HabitId)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveHabitNote' : IDL.Func([HabitId, IDL.Text, IDL.Text], [], []),
    'saveMood' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setAdminPrincipal' : IDL.Func([IDL.Principal], [], []),
    'setHabitGoal' : IDL.Func([HabitId, IDL.Text, IDL.Nat, IDL.Text], [], []),
    'setHabitReminderTime' : IDL.Func([HabitId, IDL.Text, IDL.Text], [], []),
    'setWeeklyChallenge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'spendStreakToken' : IDL.Func([HabitId, IDL.Text], [], []),
    'toggleCompletion' : IDL.Func([HabitId, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'updateHabit' : IDL.Func(
        [HabitId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };